# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:16.14
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
  deploy:
    description: |
      This job takes the built and tested source code from the test job and pushes it back up to the gh-pages branch for live deployment
    environment:
      BRANCH: gh-pages
      DIRECTORY: _site
    executor: medium
    parameters:
      fingerprint:
        default: ""
        description: ssh key fingerprint from CircleCI to push site back to repo
        type: string
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - << parameters.fingerprint >>
    - run: |
        echo $DIRECTORY
        echo $BRANCH
    - run: git fetch origin $BRANCH || git checkout --orphan gh-pages && git reset
        --hard && git config --global user.name "github-pages-orb" &&  git config
        --global user.email "github-pages-orb@example.com" && git commit --allow-empty
        -m "Init" && git checkout master
    - run: rm -rf $DIRECTORY
    - run: ls -alR
    - run: git worktree add $DIRECTORY $BRANCH
    - attach_workspace:
        at: ~/project
    - run: ls -alR
    - run: git status
    - run: |
        git config --global user.email "sean@seanhay.com"
        git config --global user.name "Sean"
    - run: |
        cd $DIRECTORY
        git add -A
        git commit -m "[skip ci] Deploy-updates"
        git push origin gh-pages -f

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  build:
    jobs:
      - build
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
      - deploy